/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ImportRouteImport } from './routes/import'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SegmentsIndexRouteImport } from './routes/segments.index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CopilotIndexRouteImport } from './routes/copilot.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as SegmentsNewRouteImport } from './routes/segments.new'
import { Route as SegmentsIdRouteImport } from './routes/segments.$id'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CopilotThreadIdRouteImport } from './routes/copilot.$threadId'
import { Route as CommunicationsIdRouteImport } from './routes/communications.$id'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AgentRunIdRouteImport } from './routes/agent.$runId'
import { Route as ApiPublicReceiptsRouteImport } from './routes/api/public/receipts'
import { Route as ApiPublicChannelTickRouteImport } from './routes/api/public/channel/tick'
import { Route as ApiPublicChannelSendRouteImport } from './routes/api/public/channel/send'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsIndexRoute = SegmentsIndexRouteImport.update({
  id: '/segments/',
  path: '/segments/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotIndexRoute = CopilotIndexRouteImport.update({
  id: '/copilot/',
  path: '/copilot/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsNewRoute = SegmentsNewRouteImport.update({
  id: '/segments/new',
  path: '/segments/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsIdRoute = SegmentsIdRouteImport.update({
  id: '/segments/$id',
  path: '/segments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotThreadIdRoute = CopilotThreadIdRouteImport.update({
  id: '/copilot/$threadId',
  path: '/copilot/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsIdRoute = CommunicationsIdRouteImport.update({
  id: '/communications/$id',
  path: '/communications/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRunIdRoute = AgentRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AgentRoute,
} as any)
const ApiPublicReceiptsRoute = ApiPublicReceiptsRouteImport.update({
  id: '/api/public/receipts',
  path: '/api/public/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChannelTickRoute = ApiPublicChannelTickRouteImport.update({
  id: '/api/public/channel/tick',
  path: '/api/public/channel/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChannelSendRoute = ApiPublicChannelSendRouteImport.update({
  id: '/api/public/channel/send',
  path: '/api/public/channel/send',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/agent/$runId': typeof AgentRunIdRoute
  '/api/chat': typeof ApiChatRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/communications/$id': typeof CommunicationsIdRoute
  '/copilot/$threadId': typeof CopilotThreadIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/segments/$id': typeof SegmentsIdRoute
  '/segments/new': typeof SegmentsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/copilot/': typeof CopilotIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/segments/': typeof SegmentsIndexRoute
  '/api/public/receipts': typeof ApiPublicReceiptsRoute
  '/api/public/channel/send': typeof ApiPublicChannelSendRoute
  '/api/public/channel/tick': typeof ApiPublicChannelTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/agent/$runId': typeof AgentRunIdRoute
  '/api/chat': typeof ApiChatRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/communications/$id': typeof CommunicationsIdRoute
  '/copilot/$threadId': typeof CopilotThreadIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/segments/$id': typeof SegmentsIdRoute
  '/segments/new': typeof SegmentsNewRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/copilot': typeof CopilotIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/segments': typeof SegmentsIndexRoute
  '/api/public/receipts': typeof ApiPublicReceiptsRoute
  '/api/public/channel/send': typeof ApiPublicChannelSendRoute
  '/api/public/channel/tick': typeof ApiPublicChannelTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/import': typeof ImportRoute
  '/insights': typeof InsightsRoute
  '/orders': typeof OrdersRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/agent/$runId': typeof AgentRunIdRoute
  '/api/chat': typeof ApiChatRoute
  '/campaigns/$id': typeof CampaignsIdRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/communications/$id': typeof CommunicationsIdRoute
  '/copilot/$threadId': typeof CopilotThreadIdRoute
  '/customers/$id': typeof CustomersIdRoute
  '/segments/$id': typeof SegmentsIdRoute
  '/segments/new': typeof SegmentsNewRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/copilot/': typeof CopilotIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/segments/': typeof SegmentsIndexRoute
  '/api/public/receipts': typeof ApiPublicReceiptsRoute
  '/api/public/channel/send': typeof ApiPublicChannelSendRoute
  '/api/public/channel/tick': typeof ApiPublicChannelTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/analytics'
    | '/import'
    | '/insights'
    | '/orders'
    | '/settings'
    | '/simulator'
    | '/agent/$runId'
    | '/api/chat'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/communications/$id'
    | '/copilot/$threadId'
    | '/customers/$id'
    | '/segments/$id'
    | '/segments/new'
    | '/campaigns/'
    | '/copilot/'
    | '/customers/'
    | '/segments/'
    | '/api/public/receipts'
    | '/api/public/channel/send'
    | '/api/public/channel/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/analytics'
    | '/import'
    | '/insights'
    | '/orders'
    | '/settings'
    | '/simulator'
    | '/agent/$runId'
    | '/api/chat'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/communications/$id'
    | '/copilot/$threadId'
    | '/customers/$id'
    | '/segments/$id'
    | '/segments/new'
    | '/campaigns'
    | '/copilot'
    | '/customers'
    | '/segments'
    | '/api/public/receipts'
    | '/api/public/channel/send'
    | '/api/public/channel/tick'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/analytics'
    | '/import'
    | '/insights'
    | '/orders'
    | '/settings'
    | '/simulator'
    | '/agent/$runId'
    | '/api/chat'
    | '/campaigns/$id'
    | '/campaigns/new'
    | '/communications/$id'
    | '/copilot/$threadId'
    | '/customers/$id'
    | '/segments/$id'
    | '/segments/new'
    | '/campaigns/'
    | '/copilot/'
    | '/customers/'
    | '/segments/'
    | '/api/public/receipts'
    | '/api/public/channel/send'
    | '/api/public/channel/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ImportRoute: typeof ImportRoute
  InsightsRoute: typeof InsightsRoute
  OrdersRoute: typeof OrdersRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  ApiChatRoute: typeof ApiChatRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  CommunicationsIdRoute: typeof CommunicationsIdRoute
  CopilotThreadIdRoute: typeof CopilotThreadIdRoute
  CustomersIdRoute: typeof CustomersIdRoute
  SegmentsIdRoute: typeof SegmentsIdRoute
  SegmentsNewRoute: typeof SegmentsNewRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  CopilotIndexRoute: typeof CopilotIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  SegmentsIndexRoute: typeof SegmentsIndexRoute
  ApiPublicReceiptsRoute: typeof ApiPublicReceiptsRoute
  ApiPublicChannelSendRoute: typeof ApiPublicChannelSendRoute
  ApiPublicChannelTickRoute: typeof ApiPublicChannelTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments/': {
      id: '/segments/'
      path: '/segments'
      fullPath: '/segments/'
      preLoaderRoute: typeof SegmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot/': {
      id: '/copilot/'
      path: '/copilot'
      fullPath: '/copilot/'
      preLoaderRoute: typeof CopilotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments/new': {
      id: '/segments/new'
      path: '/segments/new'
      fullPath: '/segments/new'
      preLoaderRoute: typeof SegmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments/$id': {
      id: '/segments/$id'
      path: '/segments/$id'
      fullPath: '/segments/$id'
      preLoaderRoute: typeof SegmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot/$threadId': {
      id: '/copilot/$threadId'
      path: '/copilot/$threadId'
      fullPath: '/copilot/$threadId'
      preLoaderRoute: typeof CopilotThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications/$id': {
      id: '/communications/$id'
      path: '/communications/$id'
      fullPath: '/communications/$id'
      preLoaderRoute: typeof CommunicationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$runId': {
      id: '/agent/$runId'
      path: '/$runId'
      fullPath: '/agent/$runId'
      preLoaderRoute: typeof AgentRunIdRouteImport
      parentRoute: typeof AgentRoute
    }
    '/api/public/receipts': {
      id: '/api/public/receipts'
      path: '/api/public/receipts'
      fullPath: '/api/public/receipts'
      preLoaderRoute: typeof ApiPublicReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/channel/tick': {
      id: '/api/public/channel/tick'
      path: '/api/public/channel/tick'
      fullPath: '/api/public/channel/tick'
      preLoaderRoute: typeof ApiPublicChannelTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/channel/send': {
      id: '/api/public/channel/send'
      path: '/api/public/channel/send'
      fullPath: '/api/public/channel/send'
      preLoaderRoute: typeof ApiPublicChannelSendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentRouteChildren {
  AgentRunIdRoute: typeof AgentRunIdRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentRunIdRoute: AgentRunIdRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ImportRoute: ImportRoute,
  InsightsRoute: InsightsRoute,
  OrdersRoute: OrdersRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  ApiChatRoute: ApiChatRoute,
  CampaignsIdRoute: CampaignsIdRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  CommunicationsIdRoute: CommunicationsIdRoute,
  CopilotThreadIdRoute: CopilotThreadIdRoute,
  CustomersIdRoute: CustomersIdRoute,
  SegmentsIdRoute: SegmentsIdRoute,
  SegmentsNewRoute: SegmentsNewRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  CopilotIndexRoute: CopilotIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  SegmentsIndexRoute: SegmentsIndexRoute,
  ApiPublicReceiptsRoute: ApiPublicReceiptsRoute,
  ApiPublicChannelSendRoute: ApiPublicChannelSendRoute,
  ApiPublicChannelTickRoute: ApiPublicChannelTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
